Solves issue #278
shoppingflux/shoppingfluxexport pull request #299
Opened 2018-01-23 07:19 UTC by Vincent-Coll

# Fixes #278

## Changes made
Added mecanism to detect previous order partially created, re set prices and carrier, and notify ShoppingFlux

2018-01-23 09:07 UTC, clement-hollander commented on shoppingfluxexport.php
> +                                SfLogger::getInstance()->log(SF_LOG_ORDERS, 'Order allready exists (id = ' . $order->IdOrder . '): notifying ShoppingFlux', $doEchoLog);
already

2018-01-29 12:57 UTC, clement-hollander commented on shoppingfluxexport.php
> +                                SfLogger::getInstance()->log(SF_LOG_ORDERS, 'Order allready exists (id = ' . $order->IdOrder . '): notifying ShoppingFlux', $doEchoLog);
@Vincent-Coll tu peux modifier allready par already ? merci

2018-01-29 13:31 UTC, Vincent-Coll commented
@clement-hollander 
my bad, corrected on 
https://github.com/shoppingflux/shoppingfluxexport/pull/299/commits/a199bce9fc61c2604d8fb58ccb5012af8b864dd7

2018-02-12 08:48 UTC, clement-hollander requested changes

2018-02-12 08:48 UTC, clement-hollander commented on shoppingfluxexport.php
> +                            if (! $forcedOrder && isset($orderExists['id_order']) && isset($orderExists['id_order'])) {
y'a deux fois la meme conditions la

2018-02-14 11:57 UTC, infiniweb commented
@clement-hollander any other changes required on this ?

2018-02-14 13:58 UTC, merged